# Generated by Django 4.2.13 on 2025-01-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=60)),
                ('room_created_by', models.CharField(max_length=10)),
                ('room_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=10)),
                ('fk_room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chat_app.room')),
            ],
            options={
                'db_table': 'room_users',
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_created_on'], name='room_room_cr_c31e5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomusers',
            unique_together={('fk_room_id', 'user_id')},
        ),
    ]
