# Generated by Django 4.2.13 on 2025-01-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomusers',
            unique_together={('fk_room_id', 'user_name')},
        ),
    ]
