# Generated by Django 4.2.13 on 2025-01-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_alter_roomusers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomusers',
            name='data_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
