version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  db:
    image: postgres:14
    ports:
      - "5433:5432" 
    environment:
      - POSTGRES_DB=live_support_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test123
    volumes:
      - postgres_data:/var/lib/postgresql/data


  livesupport:
    build: .
    ports:
      - "4004:4004"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DB_NAME=live_support_db
      - DB_USER=test_user
      - DB_PASSWORD=test123
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - kafka
      - db

volumes:
  postgres_data: